/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    Auth: () => import('#controllers/auth/auth_controller'),
  },
  business: {
    Business: () => import('#controllers/business/business_controller'),
  },
  creditPayments: {
    CreditPayments: () => import('#controllers/credit_payments/credit_payments_controller'),
  },
  customers: {
    Customers: () => import('#controllers/customers/customers_controller'),
  },
  discounts: {
    Discounts: () => import('#controllers/discounts/discounts_controller'),
  },
  locations: {
    Locations: () => import('#controllers/locations/locations_controller'),
  },
  permissions: {
    Permissions: () => import('#controllers/permissions/permissions_controller'),
  },
  products: {
    ProductCategories: () => import('#controllers/products/product_categories_controller'),
    Products: () => import('#controllers/products/products_controller'),
  },
  roles: {
    Roles: () => import('#controllers/roles/roles_controller'),
  },
  sales: {
    Sales: () => import('#controllers/sales/sales_controller'),
  },
  tables: {
    Tables: () => import('#controllers/tables/tables_controller'),
  },
  taxes: {
    Taxes: () => import('#controllers/taxes/taxes_controller'),
  },
  uploads: {
    Uploads: () => import('#controllers/uploads/uploads_controller'),
  },
  users: {
    Users: () => import('#controllers/users/users_controller'),
  },
  reservations: {
    Reservations: () => import('#controllers/reservations/reservations_controller'),
  },
  appointments: {
    Appointments: () => import('#controllers/appointments/appointments_controller'),
  },
  staff: {
    Staff: () => import('#controllers/staff/staff_controller'),
  },
}
