/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    Auth: () => import('#controllers/auth/auth_controller'),
  },
  locations: {
    Locations: () => import('#controllers/locations/locations_controller'),
  },
  permissions: {
    Permissions: () => import('#controllers/permissions/permissions_controller'),
  },
  roles: {
    Roles: () => import('#controllers/roles/roles_controller'),
  },
  users: {
    Users: () => import('#controllers/users/users_controller'),
  },
}
