/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BusinessSchema extends BaseModel {
  static $columns = ['address', 'businessType', 'city', 'country', 'createdAt', 'currency', 'email', 'id', 'isActive', 'logoUrl', 'name', 'phone', 'slug', 'timezone', 'updatedAt'] as const
  $columns = BusinessSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare businessType: string | null
  @column()
  declare city: string | null
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare logoUrl: string | null
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column()
  declare slug: string
  @column()
  declare timezone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CreditPaymentSchema extends BaseModel {
  static $columns = ['amount', 'businessId', 'createdAt', 'customerId', 'id', 'notes', 'paymentMethod', 'recordedBy'] as const
  $columns = CreditPaymentSchema.$columns
  @column()
  declare amount: string
  @column()
  declare businessId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare notes: string | null
  @column()
  declare paymentMethod: string
  @column()
  declare recordedBy: string
}

export class CustomerSchema extends BaseModel {
  static $columns = ['address', 'businessId', 'createdAt', 'createdBy', 'creditLimit', 'dateOfBirth', 'email', 'fullName', 'id', 'isActive', 'notes', 'outstandingBalance', 'phone', 'updatedAt'] as const
  $columns = CustomerSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare businessId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string
  @column()
  declare creditLimit: string
  @column.date()
  declare dateOfBirth: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare notes: string | null
  @column()
  declare outstandingBalance: string
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class LocationSchema extends BaseModel {
  static $columns = ['address', 'businessId', 'city', 'createdAt', 'id', 'isActive', 'isMain', 'name', 'phone', 'updatedAt'] as const
  $columns = LocationSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare businessId: string
  @column()
  declare city: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare isMain: boolean
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'module', 'name'] as const
  $columns = PermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare module: string
  @column()
  declare name: string
}

export class RolePermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'permissionId', 'roleId'] as const
  $columns = RolePermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare permissionId: string
  @column()
  declare roleId: string
}

export class RoleSchema extends BaseModel {
  static $columns = ['businessId', 'createdAt', 'description', 'hasFullAccess', 'id', 'isSystem', 'name', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column()
  declare businessId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare hasFullAccess: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isSystem: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserLocationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'locationId', 'userId'] as const
  $columns = UserLocationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare locationId: string
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['businessId', 'createdAt', 'email', 'fullName', 'id', 'isActive', 'lastLoginAt', 'mustChangePassword', 'password', 'permissionsOverride', 'phone', 'roleId', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare businessId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column()
  declare mustChangePassword: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare permissionsOverride: any | null
  @column()
  declare phone: string | null
  @column()
  declare roleId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
