/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type BusinessTransformer from '#transformers/business_transformer'
import type LocationTransformer from '#transformers/location_transformer'
import type PermissionTransformer from '#transformers/permission_transformer'
import type RoleTransformer from '#transformers/role_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type CustomerTransformer from '#transformers/customer_transformer'
import type CreditPaymentTransformer from '#transformers/credit_payment_transformer'

export namespace Data {
  export type Business = InferData<BusinessTransformer>
  export namespace Business {
    export type Variants = InferVariants<BusinessTransformer>
  }
  export type Location = InferData<LocationTransformer>
  export namespace Location {
    export type Variants = InferVariants<LocationTransformer>
  }
  export type Permission = InferData<PermissionTransformer>
  export namespace Permission {
    export type Variants = InferVariants<PermissionTransformer>
  }
  export type Role = InferData<RoleTransformer>
  export namespace Role {
    export type Variants = InferVariants<RoleTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type Customer = InferData<CustomerTransformer>
  export namespace Customer {
    export type Variants = InferVariants<CustomerTransformer>
  }
  export type CreditPayment = InferData<CreditPaymentTransformer>
  export namespace CreditPayment {
    export type Variants = InferVariants<CreditPaymentTransformer>
  }
}
